# Generated by Django 4.0.3 on 2022-03-26 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_cheese_country_alter_cheese_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cheese',
            old_name='country',
            new_name='origin',
        ),
        migrations.AlterField(
            model_name='cheese',
            name='milk',
            field=models.CharField(choices=[('cow', 'cow'), ('sheep', 'sheep'), ('goat', 'goat')], max_length=100),
        ),
        migrations.AlterField(
            model_name='cheese',
            name='type',
            field=models.CharField(choices=[('fresh', 'fresh'), ('soft', 'soft'), ('semi-firm', 'semi-firm'), ('hard', 'hard'), ('blue', 'blue')], max_length=100),
        ),
    ]
