# Generated by Django 4.0.3 on 2022-04-02 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_wine'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheese',
            name='wine',
            field=models.ManyToManyField(to='main_app.wine'),
        ),
    ]
